name: GitHub Action to calculate total stars

on:
    push:
        # paths:
        #     - "stars.js"

jobs:
    calculate-stars:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Update stars.json with new total stars
              run: |
                  stars_file="stars.json"
                  tmp=$(mktemp)
                  total_stars=$(cat $stars_file | jq -r '.days | flatten | add')
                  cat $stars_file | jq --indent 4 ".total = $total_stars" > $tmp && mv $tmp $stars_file
            - name: Commit changes
              run: |
                  git config --global user.name "GitHub Action"
                  git config --global user.email "action@github.com"
                  git add stars.json
                  git commit -m "Update stars.json"
                  git push
