name: GitHub Action to calculate total stars

on:
    push:
        # paths:
        #     - "**.py"

jobs:
    calculate-stars:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Check and update days' stars
              run: scripts/check_stars_progress.sh
            - name: Update stars.json with new total stars
              run: |
                  stars_file="stars.json"
                  tmp=$(mktemp)
                  total_stars=$(cat $stars_file | jq -r '.days | flatten | add')
                  cat $stars_file | jq --indent 4 ".total = $total_stars" > $tmp && mv $tmp $stars_file
            - name: Update README.md stars' table
              run: scripts/update_readme_stars_table.sh
            - name: Commit changes
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  if git commit -am "Update stars.json"; then
                    git push
                  fi
